// <auto-generated />
using System;
using System.Collections.Generic;
using ConfeccionesAlba_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConfeccionesAlba_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110133511_SwitchImageToComplexType")]
    partial class SwitchImageToComplexType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConfeccionesAlba_Api.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ConfeccionesAlba_Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ConfeccionesAlba_Api.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<decimal>("PriceReference")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Image", "ConfeccionesAlba_Api.Models.Item.Image#Image", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f4dbaa01-dcae-40a5-844e-d8a719393af4",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "1dacfc02-50b8-43da-a050-b0fa556224b7",
                            Name = "Publisher",
                            NormalizedName = "PUBLISHER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            ClaimType = "permission",
                            ClaimValue = "users:read",
                            RoleId = "f4dbaa01-dcae-40a5-844e-d8a719393af4"
                        },
                        new
                        {
                            Id = 1002,
                            ClaimType = "permission",
                            ClaimValue = "users:create",
                            RoleId = "f4dbaa01-dcae-40a5-844e-d8a719393af4"
                        },
                        new
                        {
                            Id = 1003,
                            ClaimType = "permission",
                            ClaimValue = "users:update",
                            RoleId = "f4dbaa01-dcae-40a5-844e-d8a719393af4"
                        },
                        new
                        {
                            Id = 1004,
                            ClaimType = "permission",
                            ClaimValue = "users:delete",
                            RoleId = "f4dbaa01-dcae-40a5-844e-d8a719393af4"
                        },
                        new
                        {
                            Id = 1005,
                            ClaimType = "permission",
                            ClaimValue = "categories:create",
                            RoleId = "f4dbaa01-dcae-40a5-844e-d8a719393af4"
                        },
                        new
                        {
                            Id = 1006,
                            ClaimType = "permission",
                            ClaimValue = "categories:update",
                            RoleId = "f4dbaa01-dcae-40a5-844e-d8a719393af4"
                        },
                        new
                        {
                            Id = 1007,
                            ClaimType = "permission",
                            ClaimValue = "categories:delete",
                            RoleId = "f4dbaa01-dcae-40a5-844e-d8a719393af4"
                        },
                        new
                        {
                            Id = 1008,
                            ClaimType = "permission",
                            ClaimValue = "items:create",
                            RoleId = "f4dbaa01-dcae-40a5-844e-d8a719393af4"
                        },
                        new
                        {
                            Id = 1009,
                            ClaimType = "permission",
                            ClaimValue = "items:update",
                            RoleId = "f4dbaa01-dcae-40a5-844e-d8a719393af4"
                        },
                        new
                        {
                            Id = 1010,
                            ClaimType = "permission",
                            ClaimValue = "items:delete",
                            RoleId = "f4dbaa01-dcae-40a5-844e-d8a719393af4"
                        },
                        new
                        {
                            Id = 1011,
                            ClaimType = "permission",
                            ClaimValue = "images:create",
                            RoleId = "f4dbaa01-dcae-40a5-844e-d8a719393af4"
                        },
                        new
                        {
                            Id = 1012,
                            ClaimType = "permission",
                            ClaimValue = "images:delete",
                            RoleId = "f4dbaa01-dcae-40a5-844e-d8a719393af4"
                        },
                        new
                        {
                            Id = 2001,
                            ClaimType = "permission",
                            ClaimValue = "categories:create",
                            RoleId = "1dacfc02-50b8-43da-a050-b0fa556224b7"
                        },
                        new
                        {
                            Id = 2002,
                            ClaimType = "permission",
                            ClaimValue = "categories:update",
                            RoleId = "1dacfc02-50b8-43da-a050-b0fa556224b7"
                        },
                        new
                        {
                            Id = 2003,
                            ClaimType = "permission",
                            ClaimValue = "categories:delete",
                            RoleId = "1dacfc02-50b8-43da-a050-b0fa556224b7"
                        },
                        new
                        {
                            Id = 2004,
                            ClaimType = "permission",
                            ClaimValue = "items:create",
                            RoleId = "1dacfc02-50b8-43da-a050-b0fa556224b7"
                        },
                        new
                        {
                            Id = 2005,
                            ClaimType = "permission",
                            ClaimValue = "items:update",
                            RoleId = "1dacfc02-50b8-43da-a050-b0fa556224b7"
                        },
                        new
                        {
                            Id = 2006,
                            ClaimType = "permission",
                            ClaimValue = "items:delete",
                            RoleId = "1dacfc02-50b8-43da-a050-b0fa556224b7"
                        },
                        new
                        {
                            Id = 2007,
                            ClaimType = "permission",
                            ClaimValue = "images:create",
                            RoleId = "1dacfc02-50b8-43da-a050-b0fa556224b7"
                        },
                        new
                        {
                            Id = 2008,
                            ClaimType = "permission",
                            ClaimValue = "images:delete",
                            RoleId = "1dacfc02-50b8-43da-a050-b0fa556224b7"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ConfeccionesAlba_Api.Models.Item", b =>
                {
                    b.HasOne("ConfeccionesAlba_Api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ConfeccionesAlba_Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ConfeccionesAlba_Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConfeccionesAlba_Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ConfeccionesAlba_Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
